default_context:
  project_name: 'codejavu'
  project_slug: 'codejavu'
  domain_main: 'codejavu.com'
  domain_staging: 'stag.codejavu.com'
  docker_swarm_stack_name_main: 'codejavu-com'
  docker_swarm_stack_name_staging: 'stag-codejavu-com'
  secret_key: '9b6175ede02c1376fc16549b925848d3e295873d722caeba78a04d6d7a4fa031'
  first_superuser: 'admin@codejavu.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.codejavu.com", "https://stag.codejavu.com", "https://codejavu.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@codejavu.com'
  postgres_password: 'password'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'codejavu.com'
  traefik_constraint_tag_staging: 'stag.codejavu.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'codejavu-backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'unnecessary-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
